# Generated by Django 2.2.5 on 2019-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190913_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='content',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
