# Generated by Django 2.2.5 on 2019-09-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190913_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
